Same feature by JavaDoc tag and Java annotation
ibissource/frank-doc pull request #73
Opened 2022-02-11 18:24 UTC by mhdirkse

2022-02-11 18:25 UTC, mhdirkse commented
Does not build yet. I need to do the following:
* Find the file(s) that miss a license and add it.
* Test running the doclet while using the newly added F!F annotations.

2022-02-15 09:04 UTC, gvanbrakel requested changes

2022-02-15 09:04 UTC, gvanbrakel commented on src/main/java/org/frankframework/frankdoc/model/Feature.java
> +	boolean hasFeature(FrankMethod method) {
Het leest niet helemaal lekker als dit wordt `Feature.DEPRECATED.hasFeature(class)`. 
Je zou `hasFeature()` kunnen hernoemen naar `isSetOn(class)`
en dan `hasOrInheritsFeature()` naar `isEffectivelySetOn(class)`

2022-02-17 11:23 UTC, mhdirkse commented on src/main/java/org/frankframework/frankdoc/model/Feature.java
> +	boolean hasFeature(FrankMethod method) {
Gedaan.

2022-02-18 08:07 UTC, gvanbrakel requested changes

2022-02-18 08:07 UTC, gvanbrakel commented on src/main/java/org/frankframework/frankdoc/model/Feature.java
> +	String featureValueIncludingInherited(FrankMethod method) throws FrankDocException {
Kan dit misschien dan ook 'valueOf()` worden?

2022-02-18 08:07 UTC, gvanbrakel commented on src/test/java/nl/nn/adapterframework/doc/Default.java
> +public @interface Default {
Het gaat vast een keer verwarrend zijn dat deze test class een zo algemene naam heeft als 'Default'. Daar kan je beter wat anders van maken.

2022-02-18 08:44 UTC, mhdirkse commented on src/main/java/org/frankframework/frankdoc/model/Feature.java
> +	String featureValueIncludingInherited(FrankMethod method) throws FrankDocException {
Gedaan.

2022-02-18 10:14 UTC, nielsm5 approved these changes
Je hebt een mooie oplossings-richting gekozen.
Vergeet niet de copyright jaartallen aan te passen waar nodig.
Voor elk bestand dat je aanraakt moet je `, 2022` toevoegen, en nieuwe bestanden moeten `2022` krijgen. (Feature.java)

Ik zet zelf nooit copyright in de tests, maar mocht je dat wel doen, ook daar natuurlijk het juiste jaar gebruiken.

2022-02-18 10:49 UTC, mhdirkse commented
Bedankt. Ik vond het leuk om deze oplossing te bedenken. De licenses zijn nu goed.

2022-02-18 11:01 UTC, mhdirkse commented
Nu zijn de licenses goed. De test class Default moet een goede license hebben omdat hij een kopie is van een productie class van het iaf project.

2022-02-18 17:16 UTC, gvanbrakel approved these changes

2022-02-18 17:16 UTC, merged